color0 #242e2a
color1 #fd4663
color2 #67e4b5
color3 #5ccad6
color4 #668dcc
color5 #93ecca
color6 #96e1e9
color7 #f2f3f2
color8 #5b6f67
color9 #fd4663
color10 #67e4b5
color11 #5ccad6
color12 #668dcc
color13 #93ecca
color14 #96e1e9
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1b221f
background            #1b221f
foreground            #f2f3f2
selection_foreground  #afb6b3
selection_background  #242e2a
active_border_color   #67e4b5
inactive_border_color #242e2a
url_color             #67e4b5

active_tab_foreground   #182520
active_tab_background   #67e4b5
inactive_tab_foreground #afb6b3
inactive_tab_background #242e2a
cursor_trail_color      #afb6b3
